import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

type MobileOpen = Record<string, boolean>;

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const [isMobileOpen, setIsMobileOpen] = useState<MobileOpen>({
    Product: false,
    Company: false,
    Connect: false,
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main>
        <header className="h-96 w-full bg-gradient-to-b from-[hsl(13,_100%,_72%)] to-[hsl(353,_100%,_62%)] px-4 py-10 ">
          <nav className="relative flex items-center justify-between">
            <Image
              src={"/images/logo.svg"}
              alt="logo"
              width="101"
              height="40"
            />
            <Image
              src={
                isOpen ? "/images/icon-close.svg" : "/images/icon-hamburger.svg"
              }
              width={isOpen ? "26" : "32"}
              height={isOpen ? "26" : "18"}
              alt="menu"
              onClick={() => setIsOpen(!isOpen)}
            />
            {isOpen && (
              <div className="absolute top-20 flex w-full flex-col items-stretch gap-4 border-2 bg-white p-5 text-center">
                {Object.keys(menuItems).map((item) => {
                  return (
                    <div
                      key={item}
                      className="relative flex flex-col items-center"
                    >
                      <div
                        className="flex flex-row items-center gap-2"
                        onClick={() =>
                          setIsMobileOpen({
                            ...isMobileOpen,
                            [item]: !isMobileOpen[item],
                          })
                        }
                      >
                        <p
                          className={`${
                            !isMobileOpen[item]
                              ? "font-ubuntu font-bold"
                              : "font-ubuntu font-normal"
                          }`}
                        >
                          {item}
                        </p>
                        <Image
                          src={"/images/icon-arrow-dark.svg"}
                          alt="arrow"
                          width="10"
                          height="7"
                          className={`${
                            isMobileOpen[item] ? "rotate-180" : ""
                          }`}
                        />
                      </div>
                      {isMobileOpen[item] && (
                        <div className="mt-4 flex w-full flex-col gap-2 rounded-2xl bg-[#efeff1] py-8">
                          {menuItems[item]!.map((subItem: string) => (
                            <p
                              key={subItem}
                              className="font-ubuntu text-gray-700"
                            >
                              {subItem}
                            </p>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })}
                <div className="my-2 w-full border"></div>
                <p className="font-ubuntu">Login</p>
                <button className="font-ubuntu self-center rounded-full bg-gradient-to-r from-[hsl(13,_100%,_72%)] to-[hsl(353,_100%,_62%)] px-10 py-3 font-bold text-white">
                  Sign Up
                </button>
              </div>
            )}
          </nav>
        </header>
      </main>
    </>
  );
}

type MenuItems = Record<string, string[]>;

const menuItems: MenuItems = {
  Product: ["Overview", "Pricing", "Marketplace", "Features", "Integrations"],
  Company: ["About", "Team", "Blog", "Careers"],
  Connect: ["Contact", "Newsletter", "LinkedIn"],
};
